3 Coin toss calculator

In [2]:
import numpy as np

In [46]:
NUM_COIN_TOSSES = 1000000
NUM_COINS = 3

In [47]:
heads = np.zeros(NUM_COINS+1)
print(heads)
for i in range(NUM_COIN_TOSSES):
    flips = np.random.randint(0, 2, NUM_COINS)
    # h, rem = np.bincount(flips, minlength=2)
    h = np.sum(flips)
    heads[h] += 1
    # print(f"Flips: {flips}, number of: {h}, heads: {heads}")

prob = heads / NUM_COIN_TOSSES
print(f"Probabilities: {prob}")

[0. 0. 0. 0.]
Probabilities: [0.124829 0.374818 0.375542 0.124811]


In [32]:
flips = np.random.randint(0, 2, NUM_COINS)
print(flips)
h, _ = np.bincount(flips, minlength=2)
print(h)

[0 0 0]
3


Birthday paradox


In [48]:
POPULATION_SIZE = 300
# number of ways a pair of people can share a birthday, assuming non leap year is 1/365. so the ways they don'w share a birthday is 1 - 1/365 = 364/365 
# fist we calculate how many such pairs be chosen before the probalilty of not finding common birthday is < 0.5

for pairs in range(1, POPULATION_SIZE):
    if ((364/365)**pairs) < 0.5:
        print (f"Number of pairs: {pairs}")
        break

Number of pairs: 253


In [ ]:
# now we find how many people are needed such that nC2 > 253
# 23C2 = 253. so with 23 people the probability of finding a pair with common birthday is > 0.5

Simulation to check the above result

In [49]:
SIMULATION_COUNT = 100000

matches = 0 
for i in range(SIMULATION_COUNT):
    a_birthday = np.random.randint(0, 364)
    b_birthday = np.random.randint(0, 364)
    # _, counts = np.unique(birthdays, return_counts=True)
    if a_birthday == b_birthday:
        matches += 1

print(f"Probability of finding a pair with common birthday: {matches/SIMULATION_COUNT}")

Probability of finding a pair with common birthday: 0.00274


In [ ]:
# simulation to find number of people required to have a 50% chance of finding a pair with common birthday

In [53]:
MIN_POPULATION_SIZE = 25
# check likelihood from 2 to min population size. find the first instance it crosses 0.5
for sample_size in range (2,MIN_POPULATION_SIZE):
    matches = 0
    for i in range(SIMULATION_COUNT):
        birthdays = np.random.randint(0, 364, sample_size)
        _, counts = np.unique(birthdays, return_counts=True)
        if np.any(counts > 1):
            matches += 1

    print (f"Sample size: {sample_size}, Probability of same birthday: {matches/SIMULATION_COUNT}")
    # if matches/SIMULATION_COUNT > 0.5:
    #     print(f"Population size required to have 50% chance of finding a pair with common birthday: {sample_size}")
    #     break

Population size required to have 50% chance of finding a pair with common birthday: 23


In [52]:
b = np.random.randint(0,30,6)
print(b)

[20 17 20 17  9 10]


In [51]:
b

array([27,  6,  6, 22, 26])